version: "3.9"

# Тестируем только user-service, который зависит от базы данных PostgreSQL.
services:
  postgres:
    image: postgres:latest
    container_name: pgdb_user_service
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - ./user-service/config/init.sql:/docker-entrypoint-initdb.d/init.sql

  user-service:
    build: ./user-service
    container_name: user_service_container
    ports:
      - "8080:8080"
    env_file:
      - ./user-service/config/.env
    depends_on:
      - postgres
